language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
         - COMPILER="CC=gcc-7 && CXX=g++-7"
      before_install: eval "${COMPILER}"
      script:
        - make zip

    - os: osx
      script:
        - make zip

    - os: windows
      install:
        - choco install mingw
        - choco install 7zip.install
      script:
        - mingw32-make zip

deploy:
     provider: releases
     api_key: $DEPLOY_KEY
     file:
         - clay.linux.zip
         - clay.macos.zip
         - clay.windows.zip
     skip_cleanup: true
     on:
         repo: andseq/clay
         tags: true
